version: "3.9"

services:
  mysql:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abalat
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    container_name: backend
    image: ghcr.io/mekbib-tekle/abalat-backend:latest
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_DATABASE: abalat
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - abalat-networks
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    container_name: frontend
    image: ghcr.io/mekbib-tekle/abalat-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_API_URL: http://backend:8000
      # - WDS_SOCKET_HOST: 127.0.0.1
    networks:
      - abalat-networks

networks:
  abalat-networks:
    driver: bridge


volumes:
  mysql_data: # Persist data between container restarts
  frontend:
